apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloWorldApp-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
    #maybe separate services, default backend and backup to the second node
spec:
  tls:
  - host:
    - example.com 
    secretName: secret-tls
  defaultBackend:
    service:
      name: helloWorld-service
      port:
        number: 8080