apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloWorldApp-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-connections: "3"
    nginx.ingress.kubernetes.io/custom-http-errors: "50*"
    nginx.ingress.kubernetes.io/default-backend: helloWorld-service
spec:
  tls:
  - host:
    - example.com 
    secretName: secret-tls
  rules: 
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloWorld-service
            port:
              number: 80